LTV_PY_3/MD3/Bai6/MyStore/MyStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from store import views
from orders import views as orders_views

router = routers.DefaultRouter()
router.register(r'store', views.ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('order/create/', orders_views.order_create, name='order_create'),
    path('order/', include('orders.urls', namespace='orders')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    path('dashboard/', include('dashboard.urls')),
    path('analysis/', include('analysis.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LTV_PY_3/MD3/Bai6/MyStore/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

LTV_PY_3/MD3/Bai6/MyStore/cart/models.py
from django.db import models

# Create your models here.

LTV_PY_3/MD3/Bai6/MyStore/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, widget=forms.HiddenInput)   

LTV_PY_3/MD3/Bai6/MyStore/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from store.models import Product, SubCategory
from .cart import Cart
from .forms import CartAddProductForm

subcategory_list = SubCategory.objects.all()

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})
    username = request.session.get('username', 0)                                                               
    return render(request, 'cart/detail.html', {'cart': cart, 
                                                'username': username,
                                                'subcategories': subcategory_list})

LTV_PY_3/MD3/Bai6/MyStore/cart/templates/cart/detail.html
{% extends "store/base.html" %}
{% load static %}
{% block body_block %}
<!-- Header Inner -->
<div class="header-inner">
	<div class="container">
		<div class="cat-nav-head">
			<div class="row">
				<div class="col-lg-12 col-12">
					<div class="menu-area">
						<!-- Main Menu -->
						<nav class="navbar navbar-expand-lg">
							<div class="navbar-collapse">
								<div class="nav-inner">
									<ul class="nav main-menu menu navbar-nav">
										<li><a href="{% url 'store:index.html'%}">Home</a></li>
										<li class="active"><a href="#">Shop<i class="ti-angle-down"></i><span
													class="new">New</span></a>
											<ul class="dropdown">
												<li><a href="{% url 'store:shop.html' 0 %}">Cửa hàng</a></li>
												<li><a href="{% url 'cart:cart_detail'%}">Giỏ hàng</a></li>
												<li><a href="{% url 'store:checkout.html'%}">Thanh toán</a></li>
											</ul>
										</li>
										<li><a href="{% url 'store:contact.html'%}">Liên hệ</a></li>
										<li><a href="{% url 'store:rss.html'%}">RSS</a></li>
									</ul>
								</div>
							</div>
						</nav>
						<!--/ End Main Menu -->
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!--/ End Header Inner -->
</header>
<!--/ End Header -->


<!-- Shopping Cart -->
<div class="shopping-cart section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<!-- Shopping Summery -->
				<table class="table shopping-summery">
					<thead>
						<tr class="main-hading">
							<th>SẢN PHẨM</th>
							<th>TÊN</th>
							<th class="text-center">ĐƠN GIÁ (đ)</th>
							<th class="text-center">SỐ LƯỢNG</th>
							<th class="text-center">THÀNH TIỀN</th>
							<th class="text-center"><i class="ti-trash remove-icon"></i></th>
						</tr>
					</thead>
					<tbody>
						{% for item in cart %}
						{% with product=item.product %}
						<tr>
							<td class="image" data-title="No"><img src="{{product.image.url}}" alt="{{product.name}}">
							</td>
							<td class="product-des" data-title="Description">
								<p class="product-name"><a
										href="{% url 'store:product.html' product.pk %}">{{product.name}}</a></p>
							</td>
							<td class="price" data-title="Price"><span>{% load humanize %}{{product.price|floatformat:0|intcomma}}</span></td>
							<td class="qty" data-title="Qty">
								<!-- Input Order -->
								<div class="input-group">
									<form action="{% url 'cart:cart_add' product.id %}" method="POST">
										{{item.update_quantity_form.quantity}}
										{{item.update_quantity_form.override}}
										{% csrf_token %}
										<input type="submit" value="&#x21bb;">
									</form>
								</div>
								<!--/ End Input Order -->
							</td>
							<td class="total-amount" data-title="Total"><span>{% load humanize %}{{item.total_price|floatformat:0|intcomma}}</span></td>
							<td class="action" data-title="Remove">
								<form action="{% url 'cart:cart_remove' product.id %}" method="POST">
									{% csrf_token %}
									<input type="submit" value="&#9746;">
								</form>
							</td>							
						</tr>
						{% endwith %}
						{% endfor %}
					</tbody>
				</table>
				<!--/ End Shopping Summery -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Total Amount -->
				<div class="total-amount">
					<div class="row">
						<div class="col-lg-8 col-md-5 col-12">

						</div>
						<div class="col-lg-4 col-md-7 col-12">
							<div class="right">
								<ul>
									<li>Tạm tính<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}}
											đ</span></li>
									<li>Giao hàng<span>Miễn phí</span></li>
									<li>Tiết kiệm<span>0 đ</span></li>
									<li class="last">Tổng đơn hàng<span>{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
								</ul>
								<div class="button5">
									
	
									<a href="{% url 'orders:order_create' %}" class="btn btn-primary">Thanh toán</a>
									<a href="{% url 'store:shop.html' 0%}" class="btn">Tiếp tục mua hàng</a>
								</div>
							</div>
						</div>
					</div>
				</div>
				<!--/ End Total Amount -->
			</div>
		</div>
	</div>
</div>
<!--/ End Shopping Cart -->
{% endblock %}