LTV_PY_3/MD3/Bai6/MyStore/MyStore/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from store import views
from orders import views as orders_views

router = routers.DefaultRouter()
router.register(r'store', views.ProductViewSet)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('order/create/', orders_views.order_create, name='order_create'),
    path('order/', include('orders.urls', namespace='orders')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/', include(router.urls)),
    path('dashboard/', include('dashboard.urls')),
    path('analysis/', include('analysis.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LTV_PY_3/MD3/Bai6/MyStore/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

LTV_PY_3/MD3/Bai6/MyStore/dashboard/urls.py
from django.urls import path
from . import views
app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard_with_pivot, name = 'dashboard_with_pivot'), 
    path('data', views.pivot_data, name = 'pivot_data'),
]

LTV_PY_3/MD3/Bai6/MyStore/dashboard/models.py
from django.db import models

# Create your models here.

LTV_PY_3/MD3/Bai6/MyStore/dashboard/views.py
from django.shortcuts import render
from django.http import JsonResponse
from store.models import Product
from django.core import serializers

# Create your views here.
def dashboard_with_pivot(request):
    return render(request, 'dashboard/dashboard_with_pivot.html', {})
def pivot_data(request):
    dataset = Product.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

LTV_PY_3/MD3/Bai6/MyStore/dashboard/templates/dashboard/dashboard_with_pivot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Dashboard with Flexmonster</title>
    <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
</head>
<body>
    <div id="pivot-table-container" data-url="{% url 'dashboard:pivot_data' %}"></div>
    <div id="pivot-chart-container"></div>

    <script>
        function processData(dataset) {
            var result = [];
            dataset = JSON.parse(dataset);
            dataset.forEach(item => result.push(item.fields));
            return result;
        }

        $.ajax({
            url: $("#pivot-table-container").attr("data-url"),
            datatype: "json",
            success: function(data) {
                var processedData = processData(data);

                // Render pivot table
                new Flexmonster({
                    container: "#pivot-table-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processedData,
                        }
                    }
                });

                // Render pivot chart
                new Flexmonster({
                    container: "#pivot-chart-container",
                    componentFolder: "https://cdn.flexmonster.com/",
                    width: "100%",
                    height: 430,
                    toolbar: true,
                    report: {
                        dataSource: {
                            type: "json",
                            data: processedData,
                        }
                    },
                    slice: {},
                    options: {
                        "viewType": "charts",
                        "chart": {
                            "type": "pie"
                        }
                    }
                });
            }
        });
    </script>
</body>
</html>